# Generated by Django 3.1.5 on 2022-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventorymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=500)),
                ('descriptiom', models.CharField(blank=True, max_length=5000, null=True)),
                ('unitprice', models.IntegerField(blank=True, null=True)),
                ('instockquantity', models.IntegerField(blank=True, null=True)),
                ('reorderlevel', models.IntegerField(blank=True, null=True)),
                ('reorderdays', models.IntegerField(blank=True, null=True)),
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('discontinued', models.BooleanField(default=False)),
            ],
        ),
    ]
