# Generated by Django 3.1.5 on 2022-01-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='identifier',
            field=models.CharField(default='DLM6OTNNXH', max_length=500),
        ),
    ]
