# Generated by Django 3.1.5 on 2022-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventorymodel_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='identifier',
            field=models.CharField(default='SC9ZV5HMBO', max_length=500),
        ),
    ]
